### ISSUE TITLE
screenshot of Project Management showing breakdown of tasks assigned to group member with a schedule

### ISSUE THREAD

**Issue by Kay0s** [flynn0087/Suds_Scheduler#12]

**Comment by Kay0s** [comment]
https://docs.google.com/document/d/1JH7DvlYBeTyIVnCWN9qi8PkuFablu-MD5gz2SziXW7c/edit?ts=6043ccc3

**Comment by Kay0s** [comment]
![image](https://user-images.githubusercontent.com/71153831/110219309-03d4e980-7e84-11eb-807f-96abf931926a.png)

**Comment by flynn0087** [comment]
issue complete
