### ISSUE TITLE
Due 3/9 Set Up Travis

### ISSUE THREAD

**Issue by Kay0s** [flynn0087/Suds_Scheduler#20]

**Comment by flynn0087** [comment]
Fixed travis fails from the lint having an issue with the node modules folder. It was fixed by changing the script in package.json from "lint": "eslint ./**/*.js",    to "lint": "eslint \"./**/*.js\"",

**Comment by Kay0s** [comment]
add on package.json - "fix": "eslint **/*.js --fix"
npm run fix
![image](https://user-images.githubusercontent.com/71153831/110255053-88446c80-7f57-11eb-80f5-688484401154.png)
